Repository thkruz/the-enhanced-scheduling-tool, pull requests merged in 2022-02, with the labels that each got.

#23 This is my master Develop as of the end of today
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Header/MemberDay/MemberDay.jsx
  frontend/src/components/Header/MemberDay/MemberDay.test.jsx
  frontend/src/components/Loading/Loading.jsx
  frontend/src/components/Loading/Loading.test.js
  frontend/src/pages/About/About.jsx
  frontend/src/pages/About/Calendar.jsx
  frontend/src/utils/useFetch/FakeComponent.jsx
  frontend/src/utils/useFetch/useFetch.jsx
  frontend/src/utils/useFetch/useFetch.test.js
Labels: User Story

#31 Lots of changes in this: useFetch, About, Calendar, StyledComponents
  frontend/package-lock.json
  frontend/public/index.html
  frontend/src/App.jsx
  frontend/src/components/Loading/Loading.jsx
  frontend/src/components/StyledComponents/Center.jsx
  frontend/src/components/StyledComponents/Container.jsx
  frontend/src/components/StyledComponents/Left.jsx
  frontend/src/components/StyledComponents/Main.jsx
  frontend/src/components/StyledComponents/Navigation.jsx
  frontend/src/components/StyledComponents/Right.jsx
  frontend/src/pages/About/About.jsx
  frontend/src/pages/About/Calendar.jsx
  frontend/src/pages/Calendar/Calendar.jsx
  frontend/src/utils/useFetch/useFetch.jsx
  server/package-lock.json
Labels: enhancement, User Story

#34 feat: fleshed out Calendar view
  frontend/src/components/StyledComponents/CalendarMonthlyLayout.jsx
  frontend/src/components/StyledComponents/CalendaryDayCard.jsx
  frontend/src/components/StyledComponents/Shift.jsx
  frontend/src/components/StyledComponents/ShiftContainer.jsx
  frontend/src/pages/Calendar/Calendar.jsx
Labels: Refactor

#47 feat: ✨ about page pulls from github api
  frontend/src/App.jsx
  frontend/src/components/StyledComponents/Card.jsx
  frontend/src/components/StyledComponents/List.jsx
  frontend/src/pages/About/About.jsx
  frontend/src/pages/About/About.test.js
Labels: Refactor

#48 refactor: 🎨 about page now accounts for ratelimiting
  frontend/src/pages/About/About.jsx
Labels: Refactor

#53 Scheduler context
  .vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/SchedulerContext.jsx
  frontend/src/pages/Calendar/Calendar.jsx
  frontend/src/pages/Calendar/Calendar.test.js
  frontend/src/utils/saveCsv.jsx
Labels: Feature

#55 Early merge of Admin
  frontend/.gitignore
  frontend/src/App.jsx
  frontend/src/components/StyledComponents/Center.jsx
  frontend/src/components/StyledComponents/Left.jsx
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Admin.test.jsx
  frontend/src/pages/Admin/AdminStyles.jsx
Labels: Feature

#56 partial pull to update an import style change
  frontend/src/components/StyledComponents/Container.jsx
  frontend/src/components/StyledComponents/Main.jsx
  frontend/src/pages/About/About.jsx
  frontend/src/pages/Admin/Admin.jsx
Labels: Refactor

#57 Completes the Add New User (to context, does not save to server which is beyond MVP)
  frontend/src/App.jsx
  frontend/src/index.js
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Admin.test.jsx
  frontend/src/pages/Admin/AdminAddNewUser.jsx/AdminAddNewUser.jsx
  frontend/src/pages/Admin/AdminAddNewUser.jsx/AdminAddNewUser.test.js
  frontend/src/pages/Admin/AdminStyles.jsx
  frontend/src/pages/Calendar/Calendar.jsx
  frontend/src/pages/UsersDetails/UsersDetails.jsx
Labels: Feature

#58 Adds feature to remove Users in Admin
  frontend/src/App.jsx
  frontend/src/SchedulerContext.jsx
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/AdminAddNewUser/AdminAddNewUser.jsx
  frontend/src/pages/Admin/AdminAddNewUser/AdminAddNewUser.test.js
  frontend/src/pages/Admin/AdminRemoveUser/AdminRemoveUser.jsx
  frontend/src/pages/Admin/AdminRemoveUser/AdminRemoveUser.test.js
Labels: Feature

#60 Admin export as csv
  frontend/src/pages/Admin/Admin.jsx
Labels: Feature

#63 Adds more cypress and unit tests
  cypress/integration/fulle2e.spec.js
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/components/ShiftDay/ShiftDay.jsx
  frontend/src/components/ShiftDay/ShiftDay.test.js
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Calendar/Calendar.jsx
  server/package-lock.json
Labels: Test

#66 More default route cypress tests and fix unit test on ShiftDay
  cypress/integration/fulle2e.spec.js
  frontend/src/components/Header/Header.jsx
  frontend/src/components/ShiftDay/ShiftDay.test.js
  frontend/src/pages/Calendar/Calendar.jsx
Labels: Test

#68 Adds tests for the admin page
  cypress/integration/fulle2e.spec.js
  cypress/support/commands.js
  cypress/support/index.js
  frontend/src/App.jsx
  package-lock.json
  package.json
Labels: Test
